### PR TITLE
Fix function type workaround

### PR DESCRIPTION
**Pull request by jan-ale**
Only the constructor of Number used to be cleared, now it should clear all functions.

### CODE REVIEW

**Comment by greggman** [comment]
this change won't work because `Function` is hidden (did you try it?)

updated the code: https://github.com/greggman/html5bytebeat/commit/e40a6e66af678a60153cd5a33cbafa892c4f23b2

**Comment by jan-ale** [comment]
I don't have any idea how to try it.

**Comment by greggman** [comment]
ok, well, I added some stuff to make it simpler. In the latest version

```
git clone https://github.com/greggman/html5bytebeat.git
cd html5bytebeat
npm i
npm start
```

*should* launch it locally

**Comment by greggman** [comment]
that assumes you have node.js installed which if you're on window use [nvm-windows](https://github.com/coreybutler/nvm-windows) and if you're on mac/linux use [nvm](https://github.com/nvm-sh/nvm)

**Pull request closed without merging**
